Update README.md
g1eny0ung/hugo-theme-dream pull request #207
Opened 2021-05-23 08:47 UTC by kuole-o

增加对小白的使用引导

2021-05-24 11:49 UTC, g1eny0ung requested changes

2021-05-24 11:49 UTC, g1eny0ung commented on README.md
> +[使用 Hugo + Dream 主题构建个人博客]（https://guole.fun/posts/hugo-blog/ “ Hugo 构建个人博客”）
## Tutorials from community

### Chinese

- [使用 Hugo + Dream 主题构建个人博客](https://guole.fun/posts/hugo-blog/)

2021-05-24 11:49 UTC, g1eny0ung commented on README.md
> +[使用 Hugo + Dream 主题构建个人博客]（https://guole.fun/posts/hugo-blog/ “ Hugo 构建个人博客”）
这样写吧。

2021-05-24 11:49 UTC, g1eny0ung commented on README.md
> +[Hugo启用 Twikoo 评论系统]（https://guole.fun/posts/hugo-twikoo/ “ Hugo 启用 Twikoo 评论系统”）
后两条我看你在第一篇里面也有链接引用，所以还是去掉吧，只保留个最相关的就 ok。

2021-05-25 15:34 UTC, kuole-o commented on README.md
> +[Hugo启用 Twikoo 评论系统]（https://guole.fun/posts/hugo-twikoo/ “ Hugo 启用 Twikoo 评论系统”）
okkk 我没问题的

2021-05-25 15:34 UTC, kuole-o commented on README.md
> +[使用 Hugo + Dream 主题构建个人博客]（https://guole.fun/posts/hugo-blog/ “ Hugo 构建个人博客”）
可的  我没问题

2021-05-26 16:33 UTC, g1eny0ung commented on README.md
> +[使用 Hugo + Dream 主题构建个人博客]（https://guole.fun/posts/hugo-blog/ “ Hugo 构建个人博客”）
所以更新一下？改完了可以 push 上来。

2021-06-01 15:28 UTC, closed without merging