-RelURL and +absURL
g1eny0ung/hugo-theme-dream pull request #294
Opened 2024-07-30 13:54 UTC by invmv

Fix can't use domain/ followed by address for github page 修复无法使用域名 / 后面为地址，适用于github page

2024-07-30 14:05 UTC, g1eny0ung commented
Could u provide an actual example for this situation? I'm not sure if the usage of `relURL` is the problem.

2024-07-30 14:27 UTC, invmv commented
我使用这个主题制作了 https://invmv.github.io/Notion-Hugo-dream/ 起初在本地没有部署的问题。
但是部署到pages就出现会请求主域名的css也就是 invmv.github.io/css 也就是相对路径。
根据https://gohugo.io/functions/urls/ 里的函数介绍，更换成[urls.AbsURL](https://gohugo.io/functions/urls/absurl/) 
baseurl并没有更换，问题得到解决。

并且左上角的返回主页会跟[urls.RelURL](https://gohugo.io/functions/urls/relurl/) 无限套娃

2024-07-30 14:30 UTC, invmv commented
更换成[urls.AbsURL](https://gohugo.io/functions/urls/absurl/) 就解决了，多语言应该切换到[urls.AbsLangURL](https://gohugo.io/functions/urls/abslangurl/)。

2024-07-30 16:18 UTC, g1eny0ung requested changes

2024-07-30 16:18 UTC, g1eny0ung commented on layouts/404.html
> +  <button class="btn my-5" @click="window.location.href = '{{ site.BaseURL | absURL }}'">{{ T "backToHome" }}</button>
使用 `absURL` 处理 `baseURL` 是无意义的，因为 `baseURL` 本身就是绝对路径。

2024-07-30 16:18 UTC, g1eny0ung commented on layouts/partials/head.html
> +<link rel="stylesheet" href="{{ "css/output.css" | absURL }}" />
参考 https://gohugo.io/functions/urls/relurl/#input-does-not-begin-with-a-slash

我觉得这里的问题在于路径的 `/` 前缀，去掉它就可以了，使用 `relURL` 不是问题的所在。

2024-07-30 16:54 UTC, invmv commented on layouts/partials/head.html
> +<link rel="stylesheet" href="{{ "css/output.css" | absURL }}" />
如果使用relURL 进入文章之后，加载的链接会是 /文章名/css/output.css

2024-07-31 01:22 UTC, g1eny0ung commented on layouts/partials/head.html
> +<link rel="stylesheet" href="{{ "css/output.css" | absURL }}" />
> 如果使用relURL 进入文章之后，加载的链接会是 /文章名/css/output.css

不会的，它是相对于 `baseURL`，可以本地试一下？

2024-07-31 02:55 UTC, invmv commented
本地无问题 因为只有一层目录 并且有都会指向/根目录。 但是部署给更多地方或者网页 最好使用绝对路径。相对路径后期更多问题

在 2024年7月31日，09:22，Yue Yang ***@***.***> 写道：

﻿

@g1eny0ung commented on this pull request.

________________________________

In layouts/partials/head.html<https://github.com/g1eny0ung/hugo-theme-dream/pull/294#discussion_r1697775935>:

> @@ -23,7 +23,7 @@
 <!-- Site Generator -->
 {{ hugo.Generator }}

-<link rel="stylesheet" href="{{ "/css/output.css" | relURL }}" />
+<link rel="stylesheet" href="{{ "css/output.css" | absURL }}" />


如果使用relURL 进入文章之后，加载的链接会是 /文章名/css/output.css

不会的，它是相对于 baseURL，可以本地试一下？

—
Reply to this email directly, view it on GitHub<https://github.com/g1eny0ung/hugo-theme-dream/pull/294#discussion_r1697775935>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BJQG42ERSC74B6NVEMOFPTDZPA363AVCNFSM6AAAAABLWN4RFGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMBYHE3DSNJZGY>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-31 03:35 UTC, g1eny0ung commented
> 本地无问题 因为只有一层目录 并且有都会指向/根目录。 但是部署给更多地方或者网页 最好使用绝对路径。相对路径后期更多问题

我不觉得绝对路径会是一个“更好“的方式，因为它强制将资源的路径绝对化，这样会对调试带来困难。这两种方式没有谁更好谁更坏，所以我不决定要去修改 `relURL` 到 `absURL`。

2024-07-31 04:21 UTC, closed without merging